services:
  knowledger:
    container_name: knowledger
    image: ghcr.io/rlparks/knowledger:main
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://root:mysecretpassword@knowledger-db:5432/local
      ABSOLUTE_DIR_PATH: /opt/knowledger
      OIDC_DISCOVERY_ENDPOINT: https://example.com/.well-known
      OIDC_CLIENT_ID: example
      OIDC_CLIENT_SECRET: example
      OIDC_USERNAME_CLAIM: preferred_username
      CREATE_ACCOUNT: exampleusername
      # proxy settings
      ADDRESS_HEADER: x-forwarded-for
      XFF_DEPTH: 1
    volumes:
      - ./labs:/opt/knowledger
    depends_on:
      - knowledger-db
  knowledger-db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - ./db:/var/lib/postgresql/data
